config/routes.rb
Rails.application.routes.draw do

	devise_for :users, :controllers => { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "welcome" => "welcome#index"
  get "dashboard" => "dashboard#index"

  resources :students 

  resources :answers 

  resources :users

  resources :posts

  resources :complaints

  resources :abouts

  resources :contacts

  resources :admin

  resources :dashboard

	resources :articles do
    resources :comments
  end

  resources :questions

  root 'welcome#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.nil?
      # if no user logged in, use a dummy user, see later
      user = User.new
    end
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :student
      can :manage, Answer
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :user
	for i in 1..24
		validates :"jawaban_#{i}", presence: true
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	belongs_to :user

	validates :title, presence: true
	validates :text, presence: true
	validates :user_id, presence: true
	validates :view, presence: true
	def self.search(term)
	  if term
	    where('title LIKE ?', "%#{term}%")
	  else
	  	all
	  end
	end
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :article
end

app/models/complaint.rb
class Complaint < ApplicationRecord
	belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
	validates :dominance, presence: true
	validates :influence, presence: true
	validates :steadiness, presence: true
	validates :compliance, presence: true
	validates :no, presence: true

	validates :no, numericality: { only_integer: true ,
	message: "Inputan no harus berupa angka"}

	validates_inclusion_of :no, :in => 1..24

	validates :no, uniqueness: true
	resourcify
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

    has_many :answers, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :articles, dependent: :destroy
    has_many :complaints

	validates :nim, presence: true
	validates :nama, presence: true
	validates :jenis_kelamin, presence: true
	validates :alamat, presence: true
	validates :tempat_lahir, presence: true
	validates :tgl_lahir, presence: true
	validates :email, presence: true
	validates :no_telepon, presence: true

	validates :nim, uniqueness: true

	validates :nim, numericality: { only_integer: true }
	validates :no_telepon, numericality: { only_integer: true }


	validates_presence_of :profile_picture

	validate :profile_picture_identifier

	mount_uploader :profile_picture, ImageUploader

	def self.search(term)
	  if term
	    where('nim LIKE ?', "%#{term}%")
	  else
	    with_role :student
	  end
	end

	after_create :assign_role

  def assign_role
    add_role(:student)
  end

	private
  def profile_picture_size_validation
    errors[:profile_picture] << "should be less than 1mb" if profile_picture.size > 1.megabytes
  end       
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
	def index
    @articles = Article.search(params[:term])
    @hotview = Article.all.order(view: :desc).limit(5)
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def show
    @user=current_user
    @article = Article.find(params[:id])
    @count = 1
    @count += @article.view
    @article.update(view: @count)
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to articles_path, notice: 'Data berhasil di simpan'
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article, notice: 'Data berhasil di ubah'
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text, :user_id, :view)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> data gagal disimpan
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, :class=> 'form-control' %>
  </p>

  <p>
    <%= form.label :text%><br>
    <%= form.text_area :text, :class=> 'form-control tambah-informasi' %>
  </p>
  <%= form.hidden_field :user_id, :value => current_user.id %>
  <%= form.hidden_field :view, :value => 0 %>
  <p>
    <%= form.submit :class=>'btn btn-success'%>
  </p>

<% end %>

app/views/articles/edit.html.erb
<div class="header-page">
  <div class="nav-page">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to image_tag("logo", :class => 'navbar-logo'), {controller: 'welcome'} %>
      </div>
      <ul class="nav nav-pills">
        <li role="presentation"><%= link_to 'Tes Karakter', answers_path %></li>
        <li role="presentation"><%= link_to 'Info Karakter', articles_path %></li>
        <li role="presentation"><%= link_to 'Contact Us', contacts_path %></li>
        <li role="presentation"><%= link_to 'About Us', abouts_path %></li>
      </ul>
      <ul class="nav nav-pills navbar-right">
        <div class="navbar-text pull-right">
          <% if user_signed_in? %>
            <% if current_user.has_role? :admin %>
          <%= if !current_user.nil?
                current_user.email + ' (' + current_user.roles.pluck(:name).join(",") + ')'
          end%>
        <% else %>
          <%= if !current_user.nil?
                current_user.email + ' (user)'
          end%>     
        <% end %>
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> 
            <%= link_to "Profil", current_user, :class => 'navbar-link' %> 
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> 
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </div>    
      </ul>
    </div>
  </div>
</div>
<div class="body-page">
    <div class="container">
			<h2 class="text-center">Edit Informasi</h2>	
			<%= render 'form' %>
			<%= link_to 'Back', articles_path %>
    </div>
</div>
<div class="footer">
    <div class="container">
        &copy; 2017. Designed by CYC Team.
    </div>
</div>

app/views/articles/index.html.erb
<div class="header-page">
  <div class="nav-page">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to image_tag("logo", :class => 'navbar-logo'), {controller: 'welcome'} %>
      </div>
      <ul class="nav nav-pills">
        <li role="presentation"><%= link_to 'Tes Karakter', answers_path %></li>
        <li role="presentation"><%= link_to 'Info Karakter', articles_path %></li>
        <li role="presentation"><%= link_to 'Contact Us', contacts_path %></li>
        <li role="presentation"><%= link_to 'About Us', abouts_path %></li>
      </ul>
      <ul class="nav nav-pills navbar-right">
        <div class="navbar-text pull-right">
           <% if user_signed_in? %>
        <% if current_user.has_role? :admin %>
          <%= if !current_user.nil?
                current_user.email + ' (' + current_user.roles.pluck(:name).join(",") + ')'
          end%>
        <% else %>
          <%= if !current_user.nil?
                current_user.email + ' (user)'
          end%>     
        <% end %>
        <%= link_to "Profil", current_user, :class => 'navbar-link' %> 
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> 
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
        </div>    
      </ul>
    </div>
  </div>
</div>
<div class="body-page">

    <div class="container">
    <br>
    <div>
        <%= form_tag(articles_path, method: :get) do %>
          <%= text_field_tag :term, params[:term], :class => "search-article",  placeholder: "Judul" %>
          <%= submit_tag 'Search', title: nil, :class => "btn btn-info btn-sm" %>
        <% end %>
      </div>
      <br/>

    <div class="outter-form col-md-8">
  
      <% @articles.each do |article| %>
        <h2 class="judul-article"><%= link_to article.title, article_path(article) %></h2><br>
          <p class="judul-article"><%= article.text[0,100] %>....<strong><%= link_to 'Read more', article_path(article)%></strong></p>
      <% end %>

    <%= link_to 'Postingan saya', posts_path, :class=>'btn btn-info' %>
    <%= link_to 'Buat artikel', new_article_path, :class => "btn btn-success" %>
      
    </div>
    <div class="outter-form col-md-3 col-md-offset-1">
      <h4>Paling banyak dilihat:</h4>
      <br>
    <% @hotview.each do |article| %>
      <p class="judul-article"><%= link_to article.title, article_path(article) %></p>
    <% end %>
    </div>
    </div>
</div>
<div class="footer">
    <div class="container">
        &copy; 2017. Designed by CYC Team.
    </div>
</div>

app/views/articles/new.html.erb
<div class="header-page">
  <div class="nav-page">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to image_tag("logo", :class => 'navbar-logo'), {controller: 'welcome'} %>
      </div>
      <ul class="nav nav-pills">
        <li role="presentation"><%= link_to 'Tes Karakter', answers_path %></li>
        <li role="presentation"><%= link_to 'Info Karakter', articles_path %></li>
        <li role="presentation"><%= link_to 'Contact Us', contacts_path %></li>
        <li role="presentation"><%= link_to 'About Us', abouts_path %></li>
      </ul>
      <ul class="nav nav-pills navbar-right">
        <div class="navbar-text pull-right">
          <% if user_signed_in? %>
            <% if current_user.has_role? :admin %>
          <%= if !current_user.nil?
                current_user.email + ' (' + current_user.roles.pluck(:name).join(",") + ')'
          end%>
        <% else %>
          <%= if !current_user.nil?
                current_user.email + ' (user)'
          end%>     
        <% end %>
            <%= link_to "Profil", current_user, :class => 'navbar-link' %> 
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> 
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </div>    
      </ul>
    </div>
  </div>
</div>
<div class="body-page">
    <div class="container">
    <div class="outter-form">
			<h2 class="text-center">Tambah Informasi</h2>
			<%= render 'form' %>
			<%= link_to 'Back', articles_path, :class=>'btn btn-danger' %>
    </div>
    </div>
</div>
<div class="footer">
    <div class="container">
        &copy; 2017. Designed by CYC Team.
    </div>
</div>

app/views/articles/show.html.erb
<div class="header-page">
  <div class="nav-page">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to image_tag("logo", :class => 'navbar-logo'), {controller: 'welcome'} %>
      </div>
      <ul class="nav nav-pills">
        <li role="presentation"><%= link_to 'Tes Karakter', answers_path %></li>
        <li role="presentation"><%= link_to 'Info Karakter', articles_path %></li>
        <li role="presentation"><%= link_to 'Contact Us', contacts_path %></li>
        <li role="presentation"><%= link_to 'About Us', abouts_path %></li>
      </ul>
      <ul class="nav nav-pills navbar-right">
        <div class="navbar-text pull-right">
          <% if user_signed_in? %>
            <% if current_user.has_role? :admin %>
          <%= if !current_user.nil?
                current_user.email + ' (' + current_user.roles.pluck(:name).join(",") + ')'
          end%>
        <% else %>
          <%= if !current_user.nil?
                current_user.email + ' (user)'
          end%>     
        <% end %>
            <%= link_to "Profil", current_user, :class => 'navbar-link' %> 
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> 
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </div>    
      </ul>
    </div>
  </div>
</div>
<div class="body-page">
    <div class="container">
    <div class="outter-form">
      Created by:
      <%= @article.user.email %><br>
      
      <h2 class="text-center"><%= @article.title %></h2><br>
      <%= @article.text %><br/>
      <br/>
      <%= if !current_user.nil? 
        if @article.user.id == current_user.id 
          link_to 'Edit', edit_article_path(@article)
          link_to 'Hapus artikel', article_path(@article), :class=>'btn btn-sm btn-danger',
                    method: :delete, data: { confirm: 'Are you sure?' } 
          end 
        end %>
        <%= if !current_user.nil? 
        if @article.user.id == current_user.id 
          link_to 'Edit', edit_article_path(@article), :class=>'btn btn-sm btn-warning'
          end 
        end %>
</div>
      <h4>Comments</h4>
      <%= render @article.comments %>
      <h4>Add a comment:</h4>
      <%= render 'comments/form' %>
</div>
</div>
<div class="footer">
    <div class="container">
        &copy; 2017. Designed by CYC Team.
    </div>
</div>