config/routes.rb
Rails.application.routes.draw do

	devise_for :users, :controllers => { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "welcome" => "welcome#index"
  get "dashboard" => "dashboard#index"

  resources :students 

  resources :answers 

  resources :users

  resources :posts

  resources :complaints

  resources :abouts

  resources :contacts

  resources :admin

  resources :dashboard

	resources :articles do
    resources :comments
  end

  resources :questions

  root 'welcome#index'
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

    has_many :answers, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :articles, dependent: :destroy
    has_many :complaints

	validates :nim, presence: true
	validates :nama, presence: true
	validates :jenis_kelamin, presence: true
	validates :alamat, presence: true
	validates :tempat_lahir, presence: true
	validates :tgl_lahir, presence: true
	validates :email, presence: true
	validates :no_telepon, presence: true

	validates :nim, uniqueness: true

	validates :nim, numericality: { only_integer: true }
	validates :no_telepon, numericality: { only_integer: true }


	validates_presence_of :profile_picture

	validate :profile_picture_identifier

	mount_uploader :profile_picture, ImageUploader

	def self.search(term)
	  if term
	    where('nim LIKE ?', "%#{term}%")
	  else
	    with_role :student
	  end
	end

	after_create :assign_role

  def assign_role
    add_role(:student)
  end

	private
  def profile_picture_size_validation
    errors[:profile_picture] << "should be less than 1mb" if profile_picture.size > 1.megabytes
  end       
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  before_action :configure_sign_up_params, if: :devise_controller?
  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :email, :password, :password_confirmation, :nim, :nama, :jenis_kelamin, :alamat, :tempat_lahir, :tgl_lahir, :no_telepon,:kepribadian, :keterangan, :profile_picture, :remove_profile_picture])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :password_confirmation, :current_password, :nim, :nama, :jenis_kelamin, :alamat, :tempat_lahir, :tgl_lahir,:no_telepon,:kepribadian, :keterangan, :profile_picture, :remove_profile_picture])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
    end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  def new
    super
  end

  # POST /resource/unlock
  def create
    super
  end

  # GET /resource/unlock?unlock_token=abcdef
  def show
    super
  end

  # protected

  # The path used after sending unlock password instructions
  def after_sending_unlock_instructions_path_for(resource)
    super(resource)
  end

  # The path used after unlocking the resource
  def after_unlock_path_for(resource)
    super(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
  before_action :authorize, except: [:show] 
  load_and_authorize_resource :except => [:show]
	def index
    @users = User.search(params[:term]).with_role :student
    respond_to do |format|
      format.html
      format.xls # { send_data @products.to_csv(col_sep: "\t") }
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to users_path, notice: 'Data berhasil di ubah'
    else
      render 'edit'
    end
  end

  def destroy
    @countAnswer=Answer.where(user_id: @user.id).count
    @answers = Answer.where(user_id: @user.id)
    if @countAnswer>1
      @answers.each do |answer|
        answer.destroy
      end
      @user.destroy
    elsif @countAnswer<1
      @user.destroy
    else
      @answers.destroy
      @user.destroy
    end

    redirect_to users_path
  end

  private
    def authorize
      if !current_user.has_role? :admin
        redirect_to welcome_path, alert: "Anda tidak bisa mengakses halaman tersebut"
      end
    end

    def user_params
      params.require(:user).permit(:nim, :nama, :jenis_kelamin, :alamat, :tempat_lahir, :tgl_lahir, :email, :no_telepon,:kepribadian, :profile_picture, :remove_profile_picture, :term)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |form| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> data gagal disimpan
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-md-6 col-md-offset-3">
  <div class="form-grup">
  <div class="outter-form">
  <p>

    <strong>Diisi dengan NIM/No KTP/No Induk Pelajar</strong><br>

    <%= form.text_field :nim, :class => 'form-control' %>
  </p>

  <p>
    <%= form.label :nama %><br>
    <%= form.text_field :nama, :class => 'form-control' %>
  </p>

  <p>
    <%= form.radio_button :jenis_kelamin, 'Laki-laki' %>
    <%= label :jenis_kelamin_Laki_laki, 'Laki-laki' %>
    <%= form.radio_button :jenis_kelamin, 'Perempuan' %>
    <%= label :jenis_kelamin_perempuan, 'Perempuan' %>
  </p>

  <p>
    <%= form.label :alamat %><br>
    <%= form.text_area :alamat, :class => 'form-control' %>
  </p>

  <p>
    <%= form.label :tempat_lahir %><br>
    <%= form.text_field :tempat_lahir, :class => 'form-control' %>
  </p>

  <p>
    <%= form.label :tanggal_lahir %><br>
    <%= form.date_field :tgl_lahir, :class => 'form-control' %>
  </p>

  <p>
    <%= form.label :no_telepon %><br>
    <%= form.telephone_field :no_telepon, :class => 'form-control' %>
  </p>  

  <p>
    <%= form.label :email %><br>
    <%= form.email_field :email, :class => 'form-control' %>
  </p>

  <p>
    <%= form.label :profile_picture %><br>
    <%= form.file_field :profile_picture %>
    <% if form.object.profile_picture? %>
      <%= image_tag form.object.profile_picture.thumb.url %>
      <%= form.label :remove_profile_picture %>
      <%= form.check_box :remove_profile_picture %> 
    <% end %>
  </p>

  <p>
    <%= form.submit "Update User", :class=> "btn btn-success btn-block" %>
    <%= link_to 'Back', users_path, :class=>"btn btn-danger btn-block" %>
  </p>

<% end %>
</div>
</div>
</div>

app/views/users/edit.html.erb
<div class="header-page">
  <div class="nav-page">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to image_tag("logo", :class => 'navbar-logo'), {controller: 'welcome'} %>
      </div>
      <ul class="nav nav-pills">
        <li role="presentation"><%= link_to 'Pengguna', users_path %></li>
        <li role="presentation"><%= link_to 'Admin', controller: 'admin' %></li>
        <li role="presentation"><%= link_to 'Pertanyaan', questions_path %></li>
        <li role="presentation"><%= link_to 'Keluhan', complaints_path %></li>
      </ul>
      <ul class="nav nav-pills navbar-right">
        <div class="navbar-text pull-right">
          <% if user_signed_in? %>
            <% if current_user.has_role? :admin %>
          <%= if !current_user.nil?
                current_user.email + ' (' + current_user.roles.pluck(:name).join(",") + ')'
          end%>
        <% else %>
          <%= if !current_user.nil?
                current_user.email + ' (user)'
          end%>     
        <% end %>
            <%= link_to "Profil", current_user, :class => 'navbar-link' %> 
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> 
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </div>    
      </ul>
    </div>
  </div>
</div>

<div class="body-page">
<div class="container">
<h4 class="text-center">Edit <%= current_user.email %></h4>

<%= render 'form' %>
<div class="col-md-6 col-md-offset-3">

</div>
</div>

</div>
<div class="footer">
    <div class="container">
        &copy; 2017. Designed by CYC Team.
    </div>
</div>

app/views/users/index.html.erb
<div class="header-page">
  <div class="nav-page">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to image_tag("logo",:class => 'navbar-logo'), {controller: 'welcome'} %>
      </div>
      <ul class="nav nav-pills">
        <li role="presentation"><%= link_to 'Pengguna', users_path %></li>
        <li role="presentation"><%= link_to 'Admin', controller: 'admin' %></li>
        <li role="presentation"><%= link_to 'Pertanyaan', questions_path %></li>
        <li role="presentation"><%= link_to 'Keluhan', complaints_path %></li>
      </ul>
      <ul class="nav nav-pills navbar-right">
        <div class="navbar-text pull-right">
   
      <% if user_signed_in? %>
        <% if current_user.has_role? :admin %>
          <%= if !current_user.nil?
                current_user.email + ' (' + current_user.roles.pluck(:name).join(",") + ')'
          end%>
        <% else %>
          <%= if !current_user.nil?
                current_user.email + ' (user)'
          end%>     
        <% end %>
        <%= link_to "Profil", current_user, :class => 'navbar-link' %> 
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> 
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
      
      </ul>
    </div>
  </div>
</div>
<div class="body-page">
    <div>
        <%= form_tag(users_path, method: :get) do %>
          <%= text_field_tag :term, params[:term], :class => "search",  placeholder: "ID" %>
          <%= submit_tag 'Search', nim: nil, :class => "btn btn-info btn-sm" %>
        <% end %>
      </div>
      <br>
    <div class="container-fluid">
      <div class="table-responsive">
        <table class="table table-bordered table-striped">
          <thead>
            <tr class="info">
              <th>ID</th>
              <th>Nama</th>
              <th>Jenis Kelamin</th>
              <th>Alamat</th>
              <th>Tempat Lahir</th>
              <th>Tangal Lahir</th>
              <th>No Telepon</th>
              <th>Email</th>
              <th>Kepribadian</th>
              <th class="text-center">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= link_to user.nim, user_path(user), :class =>'nim' %></td>
                <td><%= user.nama %></td>
                <td><%= user.jenis_kelamin %></td>
                <td><%= user.alamat %></td>
                <td><%= user.tempat_lahir %></td>
                <td><%= user.tgl_lahir %></td>
                <td><%= user.no_telepon %></td>
                <td><%= user.email %></td>
                <td><%= user.kepribadian %></td>
                <td align="center"><%= link_to 'Edit', edit_user_path(user), :class => "btn btn-warning btn-sm" %>
                  <%= link_to 'Delete', user_path(user), :class => "btn btn-danger btn-sm",
                  method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <%= link_to "Export to Excel", users_path(format: "xls"), :class => 'btn btn-success excel' %>
</div>
<div class="footer">
    <div class="container">
        &copy; 2017. Designed by CYC Team.
    </div>
</div>

app/views/users/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String"></Data></Cell>
        <Cell><Data ss:Type="String"></Data></Cell>
        <Cell><Data ss:Type="String"></Data></Cell>
        <Cell><Data ss:Type="String"></Data></Cell>
        <Cell><Data ss:Type="String">Data User</Data></Cell>
      </Row>
      <Row></Row>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Nama</Data></Cell>
        <Cell><Data ss:Type="String">Jenis Kelamin</Data></Cell>
        <Cell><Data ss:Type="String">Alamat</Data></Cell>
        <Cell><Data ss:Type="String">Tempat Lahir</Data></Cell>
        <Cell><Data ss:Type="String">Tanggal Lahir</Data></Cell>
        <Cell><Data ss:Type="String">No Telepon</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <Cell><Data ss:Type="String">Kepribadian</Data></Cell>
      </Row>
    <% @users.each do |user| %>
      <Row>
        <Cell><Data ss:Type="String"><%= user.nim %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.nama %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.jenis_kelamin %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.alamat %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.tempat_lahir %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.tgl_lahir %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= user.no_telepon %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.kepribadian %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/users/show.html.erb
<div class="header-page">
  <div class="nav-page">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to image_tag("logo",:class => 'navbar-logo'), {controller: 'welcome'} %>
      </div>
      <ul class="nav nav-pills">
        <% if current_user.has_role? :admin %>
          <li role="presentation"><%= link_to 'Pengguna', users_path %></li>
          <li role="presentation"><%= link_to 'Admin', controller: 'admin' %></li>
          <li role="presentation"><%= link_to 'Pertanyaan', questions_path %></l
          <li role="presentation"><%= link_to 'Keluhan', complaints_path %></li>
        <% else %>
          <li role="presentation"><%= link_to 'Tes Karakter', answers_path %></li>
          <li role="presentation"><%= link_to 'Info Karakter', articles_path %></li>
          <li role="presentation"><%= link_to 'Contact Us', contacts_path %></li>
          <li role="presentation"><%= link_to 'About Us', abouts_path %></li> 
        <% end %>
      </ul>
      <ul class="nav nav-pills navbar-right">
        <div class="navbar-text pull-right">
   
      <% if user_signed_in? %>
        <% if current_user.has_role? :admin %>
          <%= if !current_user.nil?
                current_user.email + ' (' + current_user.roles.pluck(:name).join(",") + ')'
          end%>
        <% else %>
          <%= if !current_user.nil?
                current_user.email + ' (user)'
          end%>     
        <% end %>
        <%= link_to "Profil", current_user, :class => 'navbar-link' %> 
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> 
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
      
      </ul>
    </div>
  </div>
</div>
<div class="body-page">
  <div class="container">
    <div class="col-md-6 col-md-offset-3 form">
      <div class="outter-form">
          <div class="text-center foto">
             <%= image_tag @user.profile_picture_url(:thumb), :class => "img-rounded" unless @user.profile_picture.blank? %> 
          </div>
          <% if @user.has_role? :admin %>
            <h2 class="text-center title-login">Profil Admin</h2>
          <% else %>
            <h2 class="text-center title-login">Profil Peserta</h2>
          <% end %>
          <div class="table-responsive">

            <table class="table table-striped">
            
            <tbody>

            <tr>
              <td><strong>ID:</strong></td>
              <td><%= @user.nim %></td>
            </tr>

            <tr>
              <td><strong>Nama:</strong></td>
              <td><%= @user.nama %></td>
            </tr>

            <tr>
              <td><strong>Jenis Kelamin:</strong></td>
              <td><%= @user.jenis_kelamin %></td>
            </tr>

            <tr>
              <td><strong>Alamat:</strong></td>
              <td><%= @user.alamat %></td>
            </tr>

            <tr>
              <td><strong>Tempat Lahir:</strong></td>
              <td><%= @user.tempat_lahir %></td>
            </tr>

            <tr>
              <td><strong>Tanggal Lahir:</strong></td>
              <td><%= @user.tgl_lahir %></td>
            </tr>

            <tr>
              <td><strong>No Telepon:</strong></td>
              <td><%= @user.no_telepon %></td>
            </tr>

            <tr>
              <td><strong>Email:</strong></td>
              <td><%= @user.email %></td>
            </tr>

            <tr>
              <td><strong>Kepribadian:</strong></td>
              <td><%= @user.kepribadian %></td>
            </tr>
            
            </tbody>
           </table>

          </div>
          <div class="text-center">
            <% if current_user.id == @user.id %>
              <%= link_to 'Edit profile', edit_user_registration_path, :class => "btn btn-primary" %>
            <% end %>
            <% if current_user.has_role? :admin %>
              <% if current_user.id != @user.id %>
                <%= link_to 'Edit', edit_user_path(@user), :class => "btn btn-info" %> 
              <% end %>  
              <%= link_to 'Back', users_path, :class => "btn btn-success" %>  
            <% else %>
              <%= link_to 'Back', welcome_path, :class => "btn btn-success" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
</div>
<div class="footer">
    <div class="container">
        &copy; 2017. Designed by CYC Team.
    </div>
</div>