config/routes.rb
Rails.application.routes.draw do

	devise_for :users, :controllers => { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "welcome" => "welcome#index"
  get "dashboard" => "dashboard#index"

  resources :students 

  resources :answers 

  resources :users

  resources :posts

  resources :complaints

  resources :abouts

  resources :contacts

  resources :admin

  resources :dashboard

	resources :articles do
    resources :comments
  end

  resources :questions

  root 'welcome#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :user
	for i in 1..24
		validates :"jawaban_#{i}", presence: true
	end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	before_action :set_answer, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!
	load_and_authorize_resource
	def index

	end

	def new
		@user = current_user
		@answers = Question.all.order(:no)
		@answer = Answer.new
	end

	def create
		@user = current_user
		@answer = Answer.new(answer_params)
		@answers = Question.all.order(:no)
	    if @answer.save
	      redirect_to @answer
	    else
	    	render 'new'
	    end
	end

	def show
		@answer = Answer.find(params[:id])
		@user = current_user
		@result = Answer.last
		@dominance = 0
		@influence = 0
		@steadiness = 0
		@compliance = 0
		  if @result.jawaban_1 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_1 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_1 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_2 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_2 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_2 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_3 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_3 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_3 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_4 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_4 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_4 == 'Steadiness'
		  	@steadiness+=1
		  elsif @result.jawaban_4 == 'Compliance'
		  	@compliance+=1
			end

			if @result.jawaban_5 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_5 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_5 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_6 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_6 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_6 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_7 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_7 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_7 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_8 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_8 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_8 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_9 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_9 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_9 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_10 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_10 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_10 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_11 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_11 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_11 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_12 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_12 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_12 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_13 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_13 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_13 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_14 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_14 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_14 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_15 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_15 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_15 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_16 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_16 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_16 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_17 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_17 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_17 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_18 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_18 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_18 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_19 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_19 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_19 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_20 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_20 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_20 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_21 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_21 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_21 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_22 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_22 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_22 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_23 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_23 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_23 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

			if @result.jawaban_24 == 'Dominance'
		  	@dominance+=1
		  elsif @result.jawaban_24 == 'Influence'
		  	@influence+=1
		  elsif @result.jawaban_24 == 'Steadiness'
		  	@steadiness+=1
		  else
		  	@compliance+=1
			end

		@kepribadian=nil
		if @dominance>@influence && @dominance>@steadiness && @dominance>@compliance
			@kepribadian="Dominance"
		elsif @influence>@dominance && @influence>@steadiness && @influence>@compliance
			@kepribadian="Influence"
		elsif @steadiness>@influence && @steadiness>@dominance && @steadiness>@compliance
			@kepribadian="Steadiness"
		elsif @compliance>@influence && @compliance>@dominance && @compliance>@steadiness
			@kepribadian="Compliance"
		elsif @dominance==@influence && @dominance>@steadiness && @dominance>@compliance	&& @influence>@steadiness && @influence>@compliance
			@kepribadian="Antara Dominance & Influence"
		elsif ((@dominance==@steadiness) && (@dominance>@influence) && (@dominance>@compliance)	&& (@influence<@steadiness) && (@steadiness>@compliance))
			@kepribadian="Antara Dominance & Steadiness"
		elsif @dominance==@compliance && @dominance>@steadiness && @dominance>@influence	&& @compliance>@steadiness && @influence<@compliance
			@kepribadian="Antara Dominance & Compliance"
		elsif @influence==@compliance && @influence>@steadiness && @dominance<@influence	&& @compliance>@steadiness && @dominance<@compliance
			@kepribadian="Antara Influence & Compliance"
		elsif ((@influence==@steadiness) && (@influence>@dominance) && (@influence>@compliance)	&& (@steadiness>@compliance) && (@steadiness>@dominance))
			@kepribadian="Antara Influence & Steadiness"
		elsif @steadiness==@compliance && @dominance<@steadiness && @steadiness>@influence	&& @compliance>@influence && @dominance<@compliance
			@kepribadian="Antara Steadiness & Compliance"
		else
			@kepribadian="Karakter anda rumit"
		end

		@user = current_user.update_attributes(:kepribadian => @kepribadian)
	end

	private
		def set_answer
      @answer = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:jawaban_1, :jawaban_2, :jawaban_3, :jawaban_4, :jawaban_5, :jawaban_6, :jawaban_7, :jawaban_8, :jawaban_9, :jawaban_10, :jawaban_11, :jawaban_12, :jawaban_13, :jawaban_14, :jawaban_15, :jawaban_16, :jawaban_17, :jawaban_18, :jawaban_19, :jawaban_20, :jawaban_21, :jawaban_22, :jawaban_23, :jawaban_24, :user_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/index.html.erb
<div class="header-page">
  <div class="nav-page">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to image_tag("logo",:class => 'navbar-logo'), {controller: 'welcome'} %>
      </div>
      <ul class="nav nav-pills">
        <li role="presentation"><%= link_to 'Tes Karakter', answers_path %></li>
        <li role="presentation"><%= link_to 'Info Karakter', articles_path %></li>
        <li role="presentation"><%= link_to 'Contact Us', contacts_path %></li>
        <li role="presentation"><%= link_to 'About Us', abouts_path %></li>
      </ul>
      <ul class="nav nav-pills navbar-right">
        <div class="navbar-text pull-right">
   
       <% if user_signed_in? %>
        <% if current_user.has_role? :admin %>
          <%= if !current_user.nil?
                current_user.email + ' (' + current_user.roles.pluck(:name).join(",") + ')'
          end%>
        <% else %>
          <%= if !current_user.nil?
                current_user.email + ' (user)'
          end%>     
        <% end %>
        <%= link_to "Profil", current_user, :class => 'navbar-link' %> 
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> 
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
      
      </ul>
    </div>
  </div>
</div>
<div class="body-page">
<div class="col-md-6 col-md-offset-3 mulai">
	<%= link_to 'Mulai Test', new_answer_path, :class => "btn btn-success btn-block" %>
  </div>
</div>

<div class="footer">
    <div class="container">
        &copy; 2017. Designed by CYC Team.
    </div>
</div>

app/views/answers/show.html.erb
<div class="header-page">
  <div class="nav-page">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to image_tag("logo",:class => 'navbar-logo'), {controller: 'welcome'} %>
      </div>
      <ul class="nav nav-pills">
        <li role="presentation"><%= link_to 'Tes Karakter', answers_path %></li>
        <li role="presentation"><%= link_to 'Info Karakter', articles_path %></li>
        <li role="presentation"><%= link_to 'Contact Us', contacts_path %></li>
        <li role="presentation"><%= link_to 'About Us', abouts_path %></li>
      </ul>
      <ul class="nav nav-pills navbar-right">
        <div class="navbar-text pull-right">
   
       <% if user_signed_in? %>
        <% if current_user.has_role? :admin %>
          <%= if !current_user.nil?
                current_user.email + ' (' + current_user.roles.pluck(:name).join(",") + ')'
          end%>
        <% else %>
          <%= if !current_user.nil?
                current_user.email + ' (user)'
          end%>     
        <% end %>
        <%= link_to "Profil", current_user, :class => 'navbar-link' %> 
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> 
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
      
      </ul>
    </div>
  </div>
</div>
<div class="body-page">
<div class="container">
<div class="outter-form show-hasil">
  <%#= @dominance %>
  <%#= @influence %>
  <%#= @steadiness %>
  <%#= @compliance %>
	<h2 class="text-center">Karakter anda cenderung <%= current_user.kepribadian %></h2>
  <% if current_user.kepribadian == 'Dominance' %>
    <p>
      Orang yang Dominant  tinggi akan bersifat asertif (tegas) dan langsung. Biasa nya mereka sangat independen dan ambisius. Dalam pemecahan masalahnya, tipe dominan ini melakukan pendekatan yang aktif dan cepat menyelesaikan masalah. Mereka ini orang yang cukup gagah, mereka sangat menyukai tantangan dan persaingan. Mereka dipandang orang lain sebagai orang yang berkemauan keras. Oleh karena itu mereka menginginkan segala sesuatu sesuai dengan kemauan mereka. 
    </p>
  <% elsif current_user.kepribadian == 'Influence' %>
    <p>
      Tipe Influencing ini senang berteman. Mereka suka menghibur orang lain dan bersifat sosial. Dalam penyelesaian masalah atau mengerjakan sesuatu, mereka banyak mengandalkan keterampilan sosial. Orang yang bersifat interpersonal ini senang berpartisipasi dalam kelompok dan suka bekerja sama. Keterbukaan sikapnya membuat orang lain memandang dirinya sebagai pribadi yang gampang bergaul dan ramah. Biasa nya pribadi seperti ini memiliki banyak teman. Tipe antarpribadi ini, tipe orang yang emosional karena mereka mudah mengungkapkan emosi kepada orang lain, emosional disini artinya bukan mudah marah, tetapi mudah mengungkapkan isi hatinya. Mereka lebih merasa nyaman berurusan dengan emosi daripada hal lain. 
    </p>
  <% elsif current_user.kepribadian == 'Steadiness' %>
    <p>
       Orang yang bertipe Steadiness ini adalah orang yang berkeras hati, gigih, dan sabar. Mereka mendekati dan menjalani kehidupan dengan memanfaatkan standar yang terukur dan stabil. Pada umumnya mereka tidak begitu suka kejutan. Pribadi mantap ini tidak banyak menuntut dan bersifat akomodatif. Mereka sangat ramah dan memperlihatkan kesetiaannya kepada mereka yang ada disekitarnya. Mereka sangat menghargai ketulusan. Orang yang bertipe mantap ini jujur dan mengatakan apa adanya dan berharap orang lain melakukan hal yang sama. Orang lain memandang mereka sebagai orang yang tenang, berhati hati dan konsisten dalam cara mereka menjalani kehidupan. Memiliki tingkat ketabahan yang luar biasa. Mereka dapat mempertahankan fokus dan kepentingan mereka dalam jangka waktu yang lama dibandingankan orang lain yang mampu melakukan.
    </p>
  <% elsif current_user.kepribadian == 'Compliance' %>
    <p>
      Teliti, begitu sebutan untuk tipe orang ini. Tipe teliti ini sangat tertarik pada presisi (ketelitian dan kecermatan) dan juga dengan akurasi (kecepatan). Mereka menyukai segalanya serba teratur dan jelas. Dan mereka sangat fokus terhadap fakta, maunya ada bukti. Orang tipe teliti ini sangat menghargai peraturan, mereka tidak suka melanggar peraturan. Dalam beraktivitas pun begitu, menggunakan sistematis dan aturan aturan agar semuanya terkelola dengan baik. Mengatasi konflik secara tidak langsung. Dihadapan orang lain, mereka dipandang pasif dan selalu mengalah. Kayak judul lagu aja selalu mengalah. 
    </p>
  <% elsif current_user.kepribadian == 'Antara Dominance & Influence' %>
    <p>
      Orang yang Dominant  tinggi akan bersifat asertif (tegas) dan langsung. Biasa nya mereka sangat independen dan ambisius. Dalam pemecahan masalahnya, tipe dominan ini melakukan pendekatan yang aktif dan cepat menyelesaikan masalah. Mereka ini orang yang cukup gagah, mereka sangat menyukai tantangan dan persaingan. Mereka dipandang orang lain sebagai orang yang berkemauan keras. Oleh karena itu mereka menginginkan segala sesuatu sesuai dengan kemauan mereka.<br> 
      Tipe Influencing ini senang berteman. Mereka suka menghibur orang lain dan bersifat sosial. Dalam penyelesaian masalah atau mengerjakan sesuatu, mereka banyak mengandalkan keterampilan sosial. Orang yang bersifat interpersonal ini senang berpartisipasi dalam kelompok dan suka bekerja sama. Keterbukaan sikapnya membuat orang lain memandang dirinya sebagai pribadi yang gampang bergaul dan ramah. Biasa nya pribadi seperti ini memiliki banyak teman. Tipe antarpribadi ini, tipe orang yang emosional karena mereka mudah mengungkapkan emosi kepada orang lain, emosional disini artinya bukan mudah marah, tetapi mudah mengungkapkan isi hatinya. Mereka lebih merasa nyaman berurusan dengan emosi daripada hal lain. 
    </p>
  <% elsif current_user.kepribadian == 'Antara Dominance & Steadiness' %>
    <p>
      Orang yang Dominant  tinggi akan bersifat asertif (tegas) dan langsung. Biasa nya mereka sangat independen dan ambisius. Dalam pemecahan masalahnya, tipe dominan ini melakukan pendekatan yang aktif dan cepat menyelesaikan masalah. Mereka ini orang yang cukup gagah, mereka sangat menyukai tantangan dan persaingan. Mereka dipandang orang lain sebagai orang yang berkemauan keras. Oleh karena itu mereka menginginkan segala sesuatu sesuai dengan kemauan mereka.<br>
      Orang yang bertipe Steadiness ini adalah orang yang berkeras hati, gigih, dan sabar. Mereka mendekati dan menjalani kehidupan dengan memanfaatkan standar yang terukur dan stabil. Pada umumnya mereka tidak begitu suka kejutan. Pribadi mantap ini tidak banyak menuntut dan bersifat akomodatif. Mereka sangat ramah dan memperlihatkan kesetiaannya kepada mereka yang ada disekitarnya. Mereka sangat menghargai ketulusan. Orang yang bertipe mantap ini jujur dan mengatakan apa adanya dan berharap orang lain melakukan hal yang sama. Orang lain memandang mereka sebagai orang yang tenang, berhati hati dan konsisten dalam cara mereka menjalani kehidupan. Memiliki tingkat ketabahan yang luar biasa. Mereka dapat mempertahankan fokus dan kepentingan mereka dalam jangka waktu yang lama dibandingankan orang lain yang mampu melakukan.
    </p>
  <% elsif current_user.kepribadian == 'Antara Dominance & Compliance' %>
    <p>
      Orang yang Dominant  tinggi akan bersifat asertif (tegas) dan langsung. Biasa nya mereka sangat independen dan ambisius. Dalam pemecahan masalahnya, tipe dominan ini melakukan pendekatan yang aktif dan cepat menyelesaikan masalah. Mereka ini orang yang cukup gagah, mereka sangat menyukai tantangan dan persaingan. Mereka dipandang orang lain sebagai orang yang berkemauan keras. Oleh karena itu mereka menginginkan segala sesuatu sesuai dengan kemauan mereka.<br>
      Teliti, begitu sebutan untuk tipe orang ini. Tipe teliti ini sangat tertarik pada presisi (ketelitian dan kecermatan) dan juga dengan akurasi (kecepatan). Mereka menyukai segalanya serba teratur dan jelas. Dan mereka sangat fokus terhadap fakta, maunya ada bukti. Orang tipe teliti ini sangat menghargai peraturan, mereka tidak suka melanggar peraturan. Dalam beraktivitas pun begitu, menggunakan sistematis dan aturan aturan agar semuanya terkelola dengan baik. Mengatasi konflik secara tidak langsung. Dihadapan orang lain, mereka dipandang pasif dan selalu mengalah. Kayak judul lagu aja selalu mengalah. 
    </p>
  <% elsif current_user.kepribadian == 'Antara Influence & Steadiness' %>
    <p>
      Tipe Influencing ini senang berteman. Mereka suka menghibur orang lain dan bersifat sosial. Dalam penyelesaian masalah atau mengerjakan sesuatu, mereka banyak mengandalkan keterampilan sosial. Orang yang bersifat interpersonal ini senang berpartisipasi dalam kelompok dan suka bekerja sama. Keterbukaan sikapnya membuat orang lain memandang dirinya sebagai pribadi yang gampang bergaul dan ramah. Biasa nya pribadi seperti ini memiliki banyak teman. Tipe antarpribadi ini, tipe orang yang emosional karena mereka mudah mengungkapkan emosi kepada orang lain, emosional disini artinya bukan mudah marah, tetapi mudah mengungkapkan isi hatinya. Mereka lebih merasa nyaman berurusan dengan emosi daripada hal lain.<br> 
      Orang yang bertipe Steadiness ini adalah orang yang berkeras hati, gigih, dan sabar. Mereka mendekati dan menjalani kehidupan dengan memanfaatkan standar yang terukur dan stabil. Pada umumnya mereka tidak begitu suka kejutan. Pribadi mantap ini tidak banyak menuntut dan bersifat akomodatif. Mereka sangat ramah dan memperlihatkan kesetiaannya kepada mereka yang ada disekitarnya. Mereka sangat menghargai ketulusan. Orang yang bertipe mantap ini jujur dan mengatakan apa adanya dan berharap orang lain melakukan hal yang sama. Orang lain memandang mereka sebagai orang yang tenang, berhati hati dan konsisten dalam cara mereka menjalani kehidupan. Memiliki tingkat ketabahan yang luar biasa. Mereka dapat mempertahankan fokus dan kepentingan mereka dalam jangka waktu yang lama dibandingankan orang lain yang mampu melakukan.
    </p>
  <% elsif current_user.kepribadian == 'Antara Influence & Compliance' %>
    <p>
      Tipe Influencing ini senang berteman. Mereka suka menghibur orang lain dan bersifat sosial. Dalam penyelesaian masalah atau mengerjakan sesuatu, mereka banyak mengandalkan keterampilan sosial. Orang yang bersifat interpersonal ini senang berpartisipasi dalam kelompok dan suka bekerja sama. Keterbukaan sikapnya membuat orang lain memandang dirinya sebagai pribadi yang gampang bergaul dan ramah. Biasa nya pribadi seperti ini memiliki banyak teman. Tipe antarpribadi ini, tipe orang yang emosional karena mereka mudah mengungkapkan emosi kepada orang lain, emosional disini artinya bukan mudah marah, tetapi mudah mengungkapkan isi hatinya. Mereka lebih merasa nyaman berurusan dengan emosi daripada hal lain.<br>
      Teliti, begitu sebutan untuk tipe orang ini. Tipe teliti ini sangat tertarik pada presisi (ketelitian dan kecermatan) dan juga dengan akurasi (kecepatan). Mereka menyukai segalanya serba teratur dan jelas. Dan mereka sangat fokus terhadap fakta, maunya ada bukti. Orang tipe teliti ini sangat menghargai peraturan, mereka tidak suka melanggar peraturan. Dalam beraktivitas pun begitu, menggunakan sistematis dan aturan aturan agar semuanya terkelola dengan baik. Mengatasi konflik secara tidak langsung. Dihadapan orang lain, mereka dipandang pasif dan selalu mengalah. Kayak judul lagu aja selalu mengalah. 
    </p>
  <% elsif current_user.kepribadian == 'Antara Steadiness & Compliance' %>
    <p>
      Orang yang bertipe Steadiness ini adalah orang yang berkeras hati, gigih, dan sabar. Mereka mendekati dan menjalani kehidupan dengan memanfaatkan standar yang terukur dan stabil. Pada umumnya mereka tidak begitu suka kejutan. Pribadi mantap ini tidak banyak menuntut dan bersifat akomodatif. Mereka sangat ramah dan memperlihatkan kesetiaannya kepada mereka yang ada disekitarnya. Mereka sangat menghargai ketulusan. Orang yang bertipe mantap ini jujur dan mengatakan apa adanya dan berharap orang lain melakukan hal yang sama. Orang lain memandang mereka sebagai orang yang tenang, berhati hati dan konsisten dalam cara mereka menjalani kehidupan. Memiliki tingkat ketabahan yang luar biasa. Mereka dapat mempertahankan fokus dan kepentingan mereka dalam jangka waktu yang lama dibandingankan orang lain yang mampu melakukan.<br>
      Teliti, begitu sebutan untuk tipe orang ini. Tipe teliti ini sangat tertarik pada presisi (ketelitian dan kecermatan) dan juga dengan akurasi (kecepatan). Mereka menyukai segalanya serba teratur dan jelas. Dan mereka sangat fokus terhadap fakta, maunya ada bukti. Orang tipe teliti ini sangat menghargai peraturan, mereka tidak suka melanggar peraturan. Dalam beraktivitas pun begitu, menggunakan sistematis dan aturan aturan agar semuanya terkelola dengan baik. Mengatasi konflik secara tidak langsung. Dihadapan orang lain, mereka dipandang pasif dan selalu mengalah. Kayak judul lagu aja selalu mengalah. 
    </p>
  <% else %>
    <p>
      Karakter Anda Rumit
    </p>
  <% end %>
</div>
<%= link_to 'Kembali ke Halaman Utama', welcome_path, :class=>'btn btn-danger back-show' %>
</div>
</div>
<div class="footer">
    <div class="container">
        &copy; 2017. Designed by CYC Team.
    </div>
</div>



  